### ISSUE TITLE
missing app.common

### ISSUE THREAD

**Issue by stallion5632** [jamesyangget/WeChat-Mini-Program-face-recognition#4]
hello，Do you forget to upload app.common?

**Comment by Ezharjan** [comment]
I'm facing this problem too. And I found another repositry which has the same codes as this one also misses app.common.  Can you upload app.commom ?  Otherwise the current project won't work.
我目前也遇到上面用户所遇到的同样的问题，里面缺失了app.common这个脚本但是找来找去还是没有找到， 之前看到过和这个仓库具有相同代码的另一个仓库，也是这个脚本缺失的问题，请问您可以上传一下缺失的这个app.common脚本吗？
